#!/bin/sh
echo Content-type: text/html
echo ""

CONF=/etc/ddsuite/ddsuite.conf

urldecode(){
  #echo -e "$(sed 's/+/ /g; s/%/\\x/g')"
  awk 'RT{sub("%","0x",RT);RT=sprintf("%c",RT+0)}{printf"%s",$0RT}' RS=%.. 
}

#echo "$QUERY_STRING" | awk '{split($0, a, "&"); for(i in a)print(a[i]);}' > /tmp/ddsuite.conf
#echo "STA_SSID=%40%23%24%25%5E%26&STA_KEY=1232131" | awk '{split($0, a, "&"); for(i in a)print(a[i]);}' > /tmp/ddsuite.conf
echo "$QUERY_STRING" | awk '{split($0, a, "&"); for(i in a){split(a[i], r, "="); printf("%s=\"%s\"\n", r[1], r[2]);}}' > /tmp/ddsuite.conf
. /tmp/ddsuite.conf

if ! test x$STA_SSID = x; then
  STA_SSID=`echo $STA_SSID|urldecode|urldecode`
  uci set ddsuite.main.ssid=$STA_SSID
fi

if ! test x$STA_KEY = x; then
  STA_KEY=`echo $STA_KEY|urldecode|urldecode`
  uci set ddsuite.main.ssid_key=$STA_KEY
fi

if ! test x$DEV_UUID = x; then
  DEV_UUID=`echo $DEV_UUID|urldecode|urldecode`
  uci set ddting.main.uuid=$DEV_UUID
else
  uci set ddting.main.uuid="null"
fi

uci commit ddting
uci commit ddsuite

echo "{}"



