#!/bin/sh
echo Content-type: text/html
echo ""

SSIDS=$(iwlist wlan0 scanning | grep Encryption -A 1 | awk '
BEGIN {
  FS=":";
  i=0;
  printf("[")
}
{
  if(NF>1){
    i++;
    if(i > 2 && i%2){
      printf(",");
    }

    if(i%2){
      printf("{\"enc\":\"%s\",",$2);
    }else{
      printf("\"ssid\":%s}",$2);
    }
  }
}
END{
  printf("]");
}')
echo $SSIDS


