#!/bin/sh

download_and_run(){
  APP=music-box
  URL=$1
  PWD=`pwd`

  cd /tmp/
  wget "$URL" -O ${APP}.tar.gz
  tar -zxf ${APP}.tar.gz
  APP_BIN=/tmp/${APP}/ting
  $APP_BIN
  rm -f ${APP}.tar.gz
  cd $PWD
}

download_and_flash(){
  APP=music-box.bin
  URL=$1
  PWD=`pwd`

  cd /tmp/
  wget "$URL" -O ${APP}.tar.gz
  tar -zxf ${APP}.tar.gz
  if [ -e ${APP} ]; then    
    mtd -r write /tmp/${APP} firmware
  fi
}

action_rsync(){
  BOARD=`cat /proc/cmdline|awk '{print $1}'`
  if test x$BOARD = x; then
    BOARD=`dmesg |grep Kernel|awk '{print $6}'`
  fi
  if test x$BOARD = x; then
    echo "UNKNOWN BOARD"
    exit 1
  fi
  VERSION=`uci get ddsuite.main.version`
  QUERY="http://music.fadai8.cn/api/package?$BOARD&version=${VERSION}"
  # echo $QUERY
  SRC_URL=`wget -q -O- $QUERY`
  if ! test x$SRC_URL = x; then
    echo $SRC_URL
    if test $SRC_URL = "N/A"; then
      echo "NOT support this board!"
      exit 1
    fi
    download_and_run $SRC_URL
  fi
}

action_upgrade(){
  BOARD=`cat /proc/cmdline|awk '{print $1}'`
  if test x$BOARD = x; then
    BOARD=`dmesg |grep Kernel|awk '{print $6}'`
  fi
  if test x$BOARD = x; then
    echo "UNKNOWN BOARD"
    exit 1
  fi
  VERSION=`uci get ddsuite.main.version`
  QUERY="http://music.fadai8.cn/api/image?$BOARD&version=${VERSION}"
  # echo $QUERY
  SRC_URL=`wget -q -O- $QUERY`
  if ! test x$SRC_URL = x; then
    echo $SRC_URL
    if test $SRC_URL = "N/A"; then
      echo "NOT support this board or NOT need upgrade!"
      exit 1
    fi
    download_and_flash $SRC_URL
  fi
}

action_wifi_sta(){
  CONF=/etc/ddsuite/ddsuite.conf
  if [ -e $CONF ]; then
    echo "ddsuite.conf is exist"
    . $CONF
    echo $STA_SSID $STA_KEY $STA_ENC
    wifi down
    uci set wireless.@wifi-iface[0].network=wan
    uci set wireless.@wifi-iface[0].mode=sta
    if test $STA_ENC = "on"; then
      uci set wireless.@wifi-iface[0].encryption=psk-mixed
      uci set wireless.@wifi-iface[0].key=$STA_KEY
    else
      uci set wireless.@wifi-iface[0].encryption=none
      uci set wireless.@wifi-iface[0].key=
    fi
    uci set wireless.@wifi-iface[0].ssid=$STA_SSID
    wifi up
    TICK=15
    GATEWAY=
    while : ; do
      GATEWAY=`route -e|grep default|awk '{print $2}'`
      TICK=$(( $TICK - 1))
      if ! test x$GATEWAY = x; then
         echo "default gateway: $GATEWAY"
         break;
      fi
      if [ "$TICK" -eq 0 ]; then
        echo "default gateway timeout!"
        break;
      fi
      sleep 1
    done
    if test x${GATEWAY} = x; then
      echo "failed to change sta mode!"
      MAC456=`cat /sys/class/ieee80211/phy0/macaddress|awk -F ':' '{print $4$5$6}'`
      wifi down
      uci set wireless.@wifi-iface[0].network=lan
      uci set wireless.@wifi-iface[0].mode=ap
      uci set wireless.@wifi-iface[0].encryption=none
      uci set wireless.@wifi-iface[0].ssid=musicbox-$MAC456
      uci set wireless.@wifi-iface[0].key=
      wifi up
    else
      action_rsync
    fi
  else
    echo "ddsuite.conf NOT exist"
  fi
}

case $1 in
  rsync)
    action_rsync
    ;;
  upgrade)
    action_upgrade
    ;;
  wifi_sta)
    action_wifi_sta
    ;;
  *)
  echo "usage: ddsuite rsync | upgrade | wifi_sta"
  ;;
esac
