#!/bin/sh

download_and_run(){
  APP=music-box
  URL=$1
  PWD=`pwd`

  cd /tmp/
  wget "$URL" -O ${APP}.tar.gz
  tar -zxf ${APP}.tar.gz
  APP_BIN=/tmp/${APP}/ting
  $APP_BIN
  rm -f ${APP}.tar.gz
  cd $PWD
}

rsync_package(){
  BOARD=`cat /proc/cmdline|awk '{print $1}'`
  if test x$BOARD = x; then
    BOARD=`dmesg |grep Kernel|awk '{print $6}'`
  fi
  if test x$BOARD = x; then
    echo "UNKNOWN BOARD"
    exit 1
  fi
  QUERY="http://music.fadai8.cn/api/package?$BOARD"
  # echo $QUERY
  SRC_URL=`wget -q -O- $QUERY`
  if ! test x$SRC_URL = x; then
    echo $SRC_URL
    if test $SRC_URL = "N/A"; then
      echo "NOT support this board!"
      exit 1
    fi
    download_and_run $SRC_URL
  fi
}

rsync_package


