#!/bin/sh

CONF=/etc/ddsuite/ddsuite.conf

change_to_sta(){
  wifi down
  uci set wireless.@wifi-iface[0].network=wan
  uci set wireless.@wifi-iface[0].mode=sta
  uci set wireless.@wifi-iface[0].encryption=psk-mixed
  uci set wireless.@wifi-iface[0].ssid=$1
  uci set wireless.@wifi-iface[0].key=$2
  wifi up
  sleep 5
  GATEWAY=`route -e|grep default|awk '{print $2}'`
  if test x${GATEWAY} = x; then
    echo "failed to change sta mode!"
    MAC456=`cat /sys/class/ieee80211/phy0/macaddress|awk -F ':' '{print $4$5$6}'`
    wifi down
    uci set wireless.@wifi-iface[0].network=lan
    uci set wireless.@wifi-iface[0].mode=ap
    uci set wireless.@wifi-iface[0].encryption=none
    uci set wireless.@wifi-iface[0].ssid=musicbox-$MAC456
    uci set wireless.@wifi-iface[0].key=
    wifi up
  else
    /root/rsync_music
  fi
}

if [ -e $CONF ]; then
  echo "exist"
  . $CONF
  echo $STA_SSID $STA_KEY
  change_to_sta ${STA_SSID} ${STA_KEY}
else                                                  
  echo "nooo"                                         
fi

